name: Node.js Package
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '10.14.0'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn build
      - if: ${{ github.event_name == 'release' }}
        run: yarn copy
      - if: ${{ github.event_name == 'release' }}
        run: >
            cd dist;
            npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
